server:
  port: 8380
  servlet:
    context-path: /spammer
spring:
  profiles:
    active: local
  application:
    name: spammer

spammer:
  worker-notification-url: http://localhost:8381/worker/notification