server:
  tomcat:
    accesslog:
     enabled: true
     prefix: spammer
     rename-on-rotate: true
     directory: /logs
spring:
  profiles:
    active: docker
  application:
    name: ${INSTANCE_NAME}

spammer:
  message-interval-millis: ${MESSAGE_INTERVAL_MILLIS}
  worker-notification-url: ${WORKER_NOTIFICATION_URL}